### ISSUE TITLE
你好可以在顶部view中增加view吗  可以固定吗 谢谢

### ISSUE THREAD

**Issue by 18667366881** [glh239/GLHBannerView#1]
你好可以在顶部view中增加view吗  可以固定吗 谢谢

**Comment by glh239** [comment]
当然可以增加  你如果增加的是在顶部的view上  就会固定  如果增加的是在图片上的  就会跟着图片一起变化  具体还得看你布局怎么写的  我这个主要是要给你个放大的思路
